### PR TITLE
Use '-S' instead of '-s' when signing Git commits

### PR DESCRIPTION
**Pull request by noisebleed**
Update the `CONTRIBUTING.md` doc to use the correct cli flag for signing Git commits.

## Description
As per https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work the correct flag for signing commits is `-S`. 

## Motivation and Context
Avoid confusion when submitting pull requests.

- [ ] I have raised an issue to propose this change

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/alexellis/faas/blob/master/CONTRIBUTING.md) guide
- [ ] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
This project is using small-case `-s` as per the Docker/Moby project. Using a capital S will require GPG keys for everyone correct?

**Comment by noisebleed** [comment]
Apologies. I thought the doc was referring to _(GPG) signing_ instead of _signoff_.

> Using a capital S will require GPG keys for everyone correct?

Indeed.


I'm closing the PR.

**Comment by thaJeztah** [comment]
They are not mutually exclusive; my standard approach is `git commit -s -S` to have both the sign-off, and have the commit signed with GPG

**Comment by alexellis** [comment]
I think we could re-word to say that `commit -s` for sign-off is required, but `-S` for GPG signing is encouraged/desirable. @noisebleed

**Pull request closed without merging**
