### PR TITLE
Fix importpath in Go linker -X ldflag - fixes #62

### LINKED ISSUE #62: GitCommit in commands package not being updated at build time
## Expected Behaviour

This results in the following output for a brew installed CLI:
```
$ ./faas-cli version
Git Commit: thisisavalidsha
```

## Current Behaviour

Following the merge of #50 and the move of the `GitCommit` variable from the old `main` package rather than `commands` package this commit SHA isn't getting populated.

This results in the following output:
```
$ ./faas-cli version
Git Commit:
```

## Steps to Reproduce (for bugs)

1. Download the current `0.4.9` release, or build locally using `build_redist.sh` and run `./faas-cli version`

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
n/a

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
n/a

* Operating System and version (e.g. Linux, Windows, MacOS):
MacOS

* Link to your project or a code example to reproduce issue:
n/a

### PR DESCRIPTION
**Pull request by johnmccabe**
## Description

This PR fixes the importpath to fully identify the `commands` package so that the GitCommit var can be populated at build time. The associated issue was raised in #62 and originally spotted by @ems5311 - thanks!!

This will fix binaries build by the `build_redist.sh` script, with the Brew built release requiring the same update in the homebrew-core formula (ie bumping the version on the command line isn't sufficient this time).

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/alexellis/faas/blob/master/CONTRIBUTING.md))

## How Has This Been Tested?

- Built manually passing in the version ldflag option and then ran `./faas-cli version`
- Built all the platform variants via `build_redist.sh` and then ran `./faas-cli version` on MacOS and Ubuntu
- In both cases above the GitCommit was populated as expected.
```
root@ff2edcc0885b:/# /faas/faas-cli version
Git Commit: b877c56f07d5b0ab6c417cb9eeeb06126e58031a
```

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/alexellis/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by johnmccabe** [comment]
@alexellis not sure if you want to cut a release for this, but if doing so the homebrew-core formula will need to be manually updated rather than just using the bump version command. I can do this/or help if you like whenever the release is made.

**Comment by alexellis** [comment]
Can we add an automated test for this via bash - maybe in one of the scripts the CI runs?

**Comment by johnmccabe** [comment]
Can do

**Comment by ems5311** [comment]
Only issue with this PR is that in the `Dockerfile` (not redist) the `GIT_COMMIT` is not being set, therefore the version does not get set if you use `build.sh`

**Comment by alexellis** [comment]
Please let's start covering our changes with automated regression where we can.

**Comment by johnmccabe** [comment]
@alexellis whats the purpose of the `build.sh` script, it only produces a linux binary and seems redundant given the presence of the `build_redist.sh` script?

**Comment by johnmccabe** [comment]
Added a script to check the version output from the built `faas-cli` binary that is now executed during the CI run.

**Comment by alexellis** [comment]
Thank you @johnmccabe - I'll merge this now and we can try it out on travis.

**Pull request merged**
