### PR TITLE
Make gofmt fail builds

### PR DESCRIPTION
**Pull request by itscaro**
## Description

* `gofmt` to break local and CI builds 

## Motivation and Context

- [x] I have raised an issue to propose this change (#95)

## Types of changes

Build changes

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/alexellis/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Hi @itscaro,

This is an interesting idea, thanks for looking into it. We're still using Golang 1.8 across the board until our main dependencies also move to Golang 1.9. I.e. Docker and Kubernetes. The reason the pull request template requires everyone to raise a proposal for significant changes is so that folks don't end up working on things which we can't include yet.

I'd be happy to take the change for `gofmt` if you can re-push it in a generic way - i.e. run it via the build_redist.sh file?

**Comment by itscaro** [comment]
Since the go in travis is only used to do ```go get``` that why I bump it up directly from 1.7 to 1.9

I moved the ```gofmt``` verification into ```build.sh``` and ```build_redist.sh```

**Comment by itscaro** [comment]
@alexellis should we use Makefile?

https://github.com/itscaro/faas-cli/blob/d4a511d375b0180f9f8ebabad8af14013e1a6f8b/Makefile

**Comment by alexellis** [comment]
So let's start at the beginning again.

Can you add your "exit 1" code to these files?

https://github.com/alexellis/faas-cli/blob/master/Dockerfile#L7

https://github.com/alexellis/faas-cli/blob/master/Dockerfile.redist

**Comment by itscaro** [comment]
@alexellis is it ok like this?

**Comment by alexellis** [comment]
Merging! Thank you @itscaro for your patience on this one. We really value your input on the project, keep it up.

**Pull request merged**
