### PR TITLE
Add tag into version command and shorten SHA1

### PR DESCRIPTION
**Pull request by itscaro**
Expected behavior
```
$ ./faas-cli-darwin version
  ___                   _____           ____
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
      |_|

Commit: a2dd47165dc32c8d2167af155a89ab5f616b27cc
Version: dev (or tag)
```
## Motivation and Context

- [x] I have raised an issue to propose this change (#105)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/alexellis/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by ems5311** [comment]
This is cool! Looks like the version.sh test file needs to be updated to acommodate it, however.

**Comment by alexellis** [comment]
We can include the `tag` @itscaro - good idea, but can we keep the format like this?

```
./faas-cli version
  ___                   _____           ____
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
      |_|
Commit: jfdjdjpfdjdk
Version: 0.5.3
```

**Comment by johnmccabe** [comment]
@itscaro the test here will need to either be removed or updated.

https://github.com/Homebrew/homebrew-core/blob/aee70b9c2ee2882d03a8f45eded9d9b13d00caf5/Formula/faas-cli.rb#L73

**Comment by itscaro** [comment]
@johnmccabe The output will still contain the commit in its current form, so the test should still pass, shouldn't it?

**Comment by alexellis** [comment]
Looks good to me. We'd just want to try running the Homebrew ruby tests against this too.

**Comment by johnmccabe** [comment]
@itscaro I'm seeing the following (which I'm 👍 on).
```
$ ./faas-cli-darwin version
  ___                   _____           ____
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
      |_|

Commit: a2dd47165dc32c8d2167af155a89ab5f616b27cc
Version: dev
```
If this is correct can you update the PR description, and *yes* this would pass the brew test without alteration.

**Comment by alexellis** [comment]
@johnmccabe good to merge?

**Comment by itscaro** [comment]
@alexellis PR's description updated to reflect the final format. It's ok to merge 👍

**Comment by johnmccabe** [comment]
@alexellis :shipit:

**Comment by alexellis** [comment]
Let's get this merged then. Thanks to you both for seeing this one through.

**Pull request merged**
