### PR TITLE
[WIP] Use multi-stage build for CSharp

### PR DESCRIPTION
**Pull request by rorpage**
Signed-off-by: Robbie Page <rob@rorpage.com>

## Description
I have updated the csharp template to use multi-stage. The first stage is using the dotnet SDK, and the second uses the runtime.

## Motivation and Context
The dotnet images are rather large so by implementing a multi-stage build, we decrease the end function image.
- [x] I have raised an issue to propose this change ([required](https://github.com/alexellis/faas/blob/master/CONTRIBUTING.md))
[#53](https://github.com/alexellis/faas-cli/issues/53)

## How Has This Been Tested?
I updated my template locally, created a new csharp function, built, deployed, and invoked the function and saw that everything ran as expected.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/alexellis/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Thanks for this. Can you try this with a new image name including pushing to the hub?

**Comment by alexellis** [comment]
@rorpage did you say this is working now?

**Comment by alexellis** [comment]
I got:

```
exit status 145
Did you mean to run dotnet SDK commands? Please install dotnet SDK from: 
  http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
```

**Comment by rorpage** [comment]
@alexellis This has been tested locally with the `deploy.go` fix and am no longer getting the exit status message.

**Pull request merged**
